name: project environment
dependencies:

- python=3.6.2

- psutil=5.3

- pip:
    - azureml-sdk[notebooks]
    - pynacl==1.2.1
    - scipy==1.0.0
    - scikit-learn==0.19.1
    - pandas==0.23.1
    - numpy==1.14.5